### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by noborhys** [ShiromiyaG/RVC-AI-Cover-Maker-UI#1]

**Comment by ShiromiyaG** [comment]
Just run "run.bat" on windows, "run.sh" on linux

**Comment by noborhys** [comment]
Ah, I thought so, but the cmd exits on it's own like right away

**Comment by ShiromiyaG** [comment]
Oops, it's not working, I'll fix it here

**Comment by noborhys** [comment]
Sounds good!

**Comment by ShiromiyaG** [comment]
It's working now, thanks for letting me know!
